### ISSUE TITLE
Use "active Time" instead of "Seed-Time"

### ISSUE THREAD

**Issue by CWempe** [vanossj/deluge-seedtime#10]
Maybe I am misunderstanding something here.
But wouldn't it be better to use the "active time" instead of the "seed time".

My understanding is that the "seed time" is calculated by subtracting the "added" timestamp from the current timestamp.
But if I pause a torrent or it gets queued automatically for a few hours or days the tracker does not take this time into account.

Example:
I added a torrent at at 17.6.2020. (1w 2 days ago)
But It got queued for a foew days and was only active for 3d 21h.

![image](https://user-images.githubusercontent.com/1270359/85954289-a09acb00-b976-11ea-8611-0699373a2548.png)

When I set the plugin to stop seeding after 14 days the plugin shows it will stop in 4 days.

![image](https://user-images.githubusercontent.com/1270359/85954330-f4a5af80-b976-11ea-9eae-299f30b45546.png)

But it should be 11 days, I think.

Am I missing something?
Maybe this could be an option in case the current behavior is actually wanted by other users.

**Comment by vanossj** [comment]
What version of Deluge is that from?

I did some checking
with version 1.3.15, _active time_ and _seed time_ increment even when the torrent is queued
with version 2.03, _active time_ and _seed time_ are what you think they are, ie, they pause when the torrent is queued.

Based on that, going to _active time_ in version 1.3.15 won't fix anything. and in version 2.03, _seed time_ works like you expect it to.

**Comment by CWempe** [comment]
I am using 1.3.15.
Maybe the torrent in the screenshot was paused and not queued.

Thanks.
Good to know it will work as expected when I switch to v2.
