### ISSUE TITLE
Can't get this to work with deluge-web

### ISSUE THREAD

**Issue by peabnuts123** [vanossj/deluge-seedtime#2]
I've cloned/built the source for this aganist python 2.7.9 and imported it into Deluge (via deluge-web), but activating it does not seem to have any effect. There is no new menu on the left or any new columns to add to the front-end etc. What am I missing?

**Comment by vanossj** [comment]
unfortunately this doesn't support the deluge-web ui. Should work for the gtk ui. Let me know if you try that and it still doesn't work

**Comment by peabnuts123** [comment]
So sad ;_; Do you know much about the web UI stuff? Do you think it would be difficult to implement? I could have a crack at it if you don't think it would be too hard (I am a web dev). I need this haha as I run a headless server so the GTK UI is inaccessible. 

Relatedly, is there a way I could install / configure this from the CLI?

**Comment by vanossj** [comment]
You can use the gtk gui to connect to the deluge daemon on the server. You
need to install the plugin on both ends. Not as nice as the web UI, but it
works now.

I am not a web dev so I'd appreciate any contributions.

I'll try and find some time to write up some documentation.

**Comment by vanossj** [comment]
if you really want to do everything on the command linke, check out the [wiki page](https://github.com/vanossj/deluge-seedtime/wiki/Installing-on-headless-server) for what the config file looks like.

**Comment by peabnuts123** [comment]
Beautiful, thankyou!

**Comment by vanossj** [comment]
Good news! I added a webui support. I also slightly changed the config. The default stop time is its own field, not an object in the filter list. Refer to updated [wiki page](https://github.com/vanossj/deluge-seedtime/wiki/Installing-on-headless-server).

**Comment by peabnuts123** [comment]
Oh what a beautifully committed dev, great work! Love it :smile:

**Comment by gurabli** [comment]
Great job! I used to build it few years ago, but needed gtk to use. Webui is very welcome!
