### ISSUE TITLE
Can't seem to install the plugin properly

### ISSUE THREAD

**Issue by TerrorFactor** [vanossj/deluge-seedtime#3]
Hi,
I am trying to use your plugin. It seems to build properly and also seems to install (version shows 0.6), but the SeedTime-tab in the settings menu, still shows the same (old) options (so no ability to add labels, only "stop seeding after..." and "remove torrent when stopping". What am I doing wrong?

I tried on a local deluge daemon (Windows) and on a remote (ARM linux board) daemon, but both act the same.

On the ARM board, I tried removing everything from the old SeedTime plugin, but that didn't make a difference. On the Windows daemon, there was no SeedTime installed before this version.

I also tried both the master and the ratio branch, no luck with either of them.

**Comment by vanossj** [comment]
Was this with the GTK ui or the Web ui?

you mention old SeedTime, is that [gazpachoking's](https://github.com/gazpachoking/deluge-seedtime)? If so, you'll probably have to remove the old seedtime.conf too.

To do a clean install of the plugin, delete the seedtime.conf from the [config](http://dev.deluge-torrent.org/wiki/Faq#WheredoesDelugestoreitssettingsconfig) folder and replace the SeedTime-*.egg in the _config_/plugins folder with the one you built. Use the master branch. ratio is a stalled work in progress.

If you are going to use the thin client configuration where you use GTK to connect to a remote daemon, you'll need the eggs compiled from the same version of code on the local and remote.

Hopefully that helps

**Comment by TerrorFactor** [comment]
That was with the GTK ui. I did remove the old seedtime.conf. I am using the lsioarmhf/deluge-docker container. Just to be sure, I removed the container, rm -rf'ed the config folder, and recreated the container.
I downloaded the zipfile from your masterbranch again, built the plugin and installed it with the GTK ui (that comes with the Windows client). Same effect. 

Screenshot of plugin window: 
![image](https://cloud.githubusercontent.com/assets/578933/23176910/45894d8e-f865-11e6-9d49-96a90b8dbef6.png)

Screenshot of SeedTime window: 
![image](https://cloud.githubusercontent.com/assets/578933/23176874/262dcf50-f865-11e6-9eb7-d2e7b84aabb4.png)

The copy of your  branch with the built files:
[deluge-seedtime-master-built.zip](https://github.com/vanossj/deluge-seedtime/files/790955/deluge-seedtime-master-built.zip)

I don't really get it :/

**Comment by vanossj** [comment]
I don't have much experience with Docker, but I was able to start a linuxserver/deluge container (I don't have an ARM to try) and use the webui to install and configure seedtime (from the egg in the zip you attached).

I was never able to connect my local GTK ui to the docker container. So I'm still not sure the cause of the issue you are seeing.

If you had to do any configuration for docker to get a thin client to connect, let me know and I'll try it

**Comment by TerrorFactor** [comment]
Thank you for your quick responses!
What do you mean with "configure seedtime"? Just activate the plugin? 

To be able to connect to a remote client, you have to enable remote connections (settings>daemon).
You also have to set a user and password in the "auth" file in your config folder.
You should have "localclient:somehash" already there. Just add "username:password" as first line. You'll have to restart deluge, and that should be it.

Thanks again!

**Comment by vanossj** [comment]
Thanks, got thin client connected, although for some reason the default port 58846 didn't work for me, but after I changed to port 58946 it worked.

I was not able to install the plugin from the GTK gui. But I could install the plugin with the webui, or by copying the egg into the config/plugin directory. And then use the plugin in GTK

By configure the plugin, i just ment use it, add filters, etc ...

**Comment by TerrorFactor** [comment]
I tried it on a x86, and it worked without any issue. Created a second deluge container on my ARM-board, and it also worked (noticed SeedTime is also available from the webinterface, the older version I had wasn't, great improvement!).

Really weird. I'll start over, not sure what I did wrong the first time I reinstalled my Docker-container. Thank you for the quick support!
