### ISSUE TITLE
Adding seedtime automatically does not seem to work

### ISSUE THREAD

**Issue by TerrorFactor** [vanossj/deluge-seedtime#4]
![image](https://cloud.githubusercontent.com/assets/578933/23226289/5516dc50-f935-11e6-8325-fbf5dbdbf4dc.png)

Automatically adding a seedtime (default or based on tracker) doesn't seem to work properly.
Setting seedtime to 0 (or 0.1 or 0.01) means it keeps on seeding.
 ![image](https://cloud.githubusercontent.com/assets/578933/23227541/90b03cf8-f939-11e6-8a6b-a3ed7bafc552.png)

I tried different ways of specifying the tracker (alpharatio, alpharatio.*, alpharatio*, *alpharatio*, .*alpharatio.*) but none worked. Weirdly enough, it has some effect, as any torrent added from alpharatio with one of those rules (I tested mostly with alpharatio.*) does not get the default seedtime. It always gets 0 as seedtime (but keeps on seeding).

Stock queue settings (also tried setting everything to 0 and stock settings, but same effect):
![image](https://cloud.githubusercontent.com/assets/578933/23226398/b32152e4-f935-11e6-8297-f1ece368a518.png)

Tested on ARM and x64, in the linuxserver.io dockers.

**Comment by vanossj** [comment]
The filter must be a valid regular expression, so in the first image its going to break on the unescaped / and * with nothing if front is not valid regex, but alpharaio.* is definitely valid regex.

stoptime of 0 means infinite seedtime, but 0.01 should stop after seedtime of about 15 minutes. When you change things in the settings, make sure you press apply or ok and not close or the X. Doesn't seem like that would be the case but just checking.

Can you post your seedtime.conf file from the deluge config folder?

**Comment by TerrorFactor** [comment]
```
{
  "file": 1,
  "format": 1
}{
  "remove_torrent": false,
  "torrent_stop_times": {
    "3ae249715b471fd8a756559b6bfcc0a807e01d58": 3,
    "dbf63d0d9a1bc2a3d8bb55de2de59d9cc22563c5": 3,
    "dde74e7c6a1ecc7c798d53ceaa748022d756c4d9": 3,
    "3b7d161849b31f4d429a1566a6aac9af2ff8a030": 3,
    "24975607878694d3a5d0e8a768190dfd68905d68": 3,
    "8faa9b3a832a8c7b70bf7ba7a65afa20241d9c8c": 3
  },
  "filter_list": [
    {
      "filter": ".*alpharatio.*",
      "field": "tracker",
      "stoptime": 3
    }
  ],
  "default_stop_time": 0,
  "delay_time": 1
}
```

Seems that the stop-time doesn't fill in properly, maybe a localization issue? We normally use a "," for digits, but I couldn't enter that in the webinterface. Seems to be confirmed by the torrentclient, seeding doesn't stop after 15 minutes.

The regex for alpharatio seems fine (according to https://regex101.com/), it matches with the full tracker url for an alpharatio torrent.

I'll try modifying the config manually and see what that does.

**Comment by TerrorFactor** [comment]
Stopping the container, modifying the config manually (default_stop_time: 0.01) seems to work for the default rule. Seedtime is indeed ~15 minutes.

The AR-rule just gets ignored, but the default rule is not applied on those torrents. seedtime is 0, and it just keeps on seeding.

**Comment by vanossj** [comment]
Found the bug. The core plugin and gtk were using stop_time as a key in the config, but I had the webui using stoptime, which explains why the filters you created in the webui didn't work.

You'll need to build a new egg from master and replace the old egg in the config/plugin folder
Manually edit the seedtime.conf file to use "stop_time" instead of "stoptime" in the filter_list array items (or delete the conf file and start fresh)

I think that should fix it. Let me know. Thanks for helping me find this bug.

**Comment by TerrorFactor** [comment]
Seems to be okay now, thank you!
