### ISSUE TITLE
Build for latest Deluge version with Python3

### ISSUE THREAD

**Issue by gurabli** [vanossj/deluge-seedtime#7]
I can't make it work with latest Deluge 2.0.3. Do you have it working?

**Comment by vanossj** [comment]
Whoa, Deluge 2 actually happened?

I'll check it out

**Comment by gurabli** [comment]
Yeah, and it is already version 2.0.3.
They moved to Python3 if I'm correct. I tried to build the plugin with Python3 command, it built, but I can't download anything over webui. Don't know why.

**Comment by vanossj** [comment]
Try the new seedtime version 2.1

webui didn't change, but the gtk gui needed an upgrade to support gtk3 in deluge 2
